version: "3.9"
services:

  client:
    build: ./client
    env_file:
      - ./client/.env
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - server
    container_name: client

  server:
    build: ./server
    restart: always
    env_file: 
      - ./server/.env
    ports:
      - "5000"
    depends_on:
      - database
    container_name: server

  database:
    image: postgres:15.0
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5432"
    volumes:
      - dbdata:/var/lib/postgresql
    container_name: database

volumes:
  dbdata: