version: "3.9"
services:

  client:
    build: ./client
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    depends_on:
      - server
    restart: always
    # command: sh -c "tail -f /dev/null"
    container_name: client
    volumes:
      # - type: bind
      #   source: ./client
      #   target: /workspace/client
      - ./client:/workspace
      - /workspace/client/node_modules

  server:
    build: ./server
    restart: always
    env_file: 
      - ./server/.env
    ports:
      - "5000"
    depends_on:
      - database
    container_name: server
    volumes:
      # - type: bind
      #   source: ./server
      #   target: /workspace/server
      - ./server:/workspace
      - /workspace/server/node_modules

  database:
    image: postgres:15.0
    restart: always
    env_file:
      - ./server/.env
    volumes:
      - dbdata:/var/lib/postgresql
    ports:
      - "5432"
    container_name: database

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
#    user: pgadmin
    restart: always
    depends_on:
      - server
    env_file:
      - ./server/.env
      - .pgadmin.env
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - "5050:80"


volumes:
  dbdata:
