version: "3"
services:

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    container_name: client

  server:
    build: ./server
    restart: always
    environment:
      - PORT=5000
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
      - POSTGRES_PASSWORD=root
      - PRIVATE_KEY=very_secret_key
      - PG_ADMIN_PASSWORD=root
    ports:
      - "5000:5000"
    depends_on:
      - database
    container_name: server

  database:
    image: postgres:15.0
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    container_name: database