export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const GAME_ROUTE = '/game'
export const ACCOUNT_ROUTE = '/user'
export const MAIN_ROUTE = '/'
